spring:
  datasource:
    url: jdbc:oracle:thin:@programmer7771.iptime.org:1521/xe
    username: seventh
    password: seventh
    driver-class-name: oracle.jdbc.driver.OracleDriver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
